const boroughs = {
  "ba-01-altstadt-lehel": "BA 01 Altstadt – Lehel",
  "ba-02-ludwigsvorstadt-isarvorstadt": "BA 02 Ludwigsvorstadt – Isarvorstadt",
  "ba-03-maxvorstadt": "BA 03 Maxvorstadt",
  "ba-04-schwabing-west": "BA 04 Schwabing-West",
  "ba-05-au-haidhausen": "BA 05 Au – Haidhausen",
  "ba-06-sendling": "BA 06 Sendling",
  "ba-07-sendling-westpark": "BA 07 Sendling – Westpark",
  "ba-08-schwanthalerhoehe": "BA 08 Schwanthalerhöhe",
  "ba-09-neuhausen-nymphenburg": "BA 09 Neuhausen – Nymphenburg",
  "ba-10-moosach": "BA 10 Moosach",
  "ba-11-milbertshofen-am-hart": "BA 11 Milbertshofen – Am Hart",
  "ba-12-schwabing-freimann": "BA 12 Schwabing – Freimann",
  "ba-13-bogenhausen": "BA 13 Bogenhausen",
  "ba-14-berg-am-laim": "BA 14 Berg am Laim",
  "ba-15-trudering-riem": "BA 15 Trudering – Riem",
  "ba-16-ramersdorf-perlach": "BA 16 Ramersdorf – Perlach",
  "ba-17-obergiesing-fasangarten": "BA 17 Obergiesing – Fasangarten",
  "ba-18-untergiesing-harlaching": "BA 18 Untergiesing – Harlaching",
  "ba-19-thalkirchen-obersendling-forstenried-fuerstenried-solln": "BA 19 Thalkirchen – Obersendling – Forstenried – Fürstenried – Solln",
  "ba-20-hadern": "BA 20 Hadern",
  "ba-21-pasing-obermenzing": "BA 21 Pasing – Obermenzing",
  "ba-22-aubing-lochhausen-langwied": "BA 22 Aubing – Lochhausen – Langwied",
  "ba-23-allach-untermenzing": "BA 23 Allach – Untermenzing",
  "ba-24-feldmoching-hasenbergl": "BA 24 Feldmoching – Hasenbergl",
  "ba-25-laim": "BA 25 Laim",
  "landkreis-muenchen": "Landkreis München",
  "unbekannt": "Unbekannt"
}

module.exports = boroughs
