const contexts = {
  "arbeitsplatz": "Arbeitsplatz",
  "aufkleber-plakataktion": "Aufkleber/Plakataktion",
  "brief": "Brief",
  "demonstration": "Demonstration",
  "diskussions-vortragsveranstaltung-intern": "Diskussions-/Vortragsveranstaltung intern",
  "diskussions-vortragsveranstaltung-oeffentlich": "Diskussions-/Vortragsveranstaltung öffentlich",
  "einzelhandel": "Einzelhandel",
  "flugblattverteilaktion": "Flugblattverteilaktion",
  "gefluechtetenunterkunft": "Geflüchtetenunterkunft",
  "infostand": "Infostand",
  "internet-soziale-netzwerke": "Internet/Soziale Netzwerke",
  "konzert": "Konzert",
  "kundgebungmahnwache": "Kundgebung/Mahnwache",
  "lokal-restaurant-club": "Lokal/Restaurant/Club",
  "mail": "Mail",
  "nachbarschaft-wohnumfeld": "Nachbarschaft/Wohnumfeld",
  "oeffentliche-institution": "Öffentliche Institution",
  "oeffentlicher-raum-allgemein": "Öffentlicher Raum allgemein",
  "oepnv": "ÖPNV",
  "polizei": "Polizei",
  "private-institution": "Private Institution",
  "schule-hochschule-universitaet": "Schule/Hochschule/Universität",
  "sonstiges": "Sonstiges",
  "sportveranstaltung": "Sportveranstaltung",
  "telefonanruf": "Telefonanruf",
}

module.exports = contexts
